#!/bin/bash

### BEGIN INIT INFO
# Provides:        isc-dhcp-server
# Required-Start:  $remote_fs $network $syslog
# Required-Stop:   $remote_fs $network $syslog
# Should-Start:    $local_fs slapd $named
# Should-Stop:     $local_fs slapd
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start MOE DHCP daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case $1 in
        start)
		start-stop-daemon -S --exec /home/roma2lug/moe-receiver/moe-receiver -b
		;;
        *)
                echo "Usage: $0 {start|e non rompere i coglioni}"
                exit 2
                ;;
esac

